version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - npm test
      - npm run cdk:synth
  post_build:
    commands:
      - echo Build completed on `date`
